import { api } from './api.js';
import { mountPortal, heading, stat, table, items, badge, escapeHtml, showModal, setLoading, empty, toast } from './common.js';

const page=document.body.dataset.page;
const content=()=>document.querySelector('#content');
async function dashboard(){const root=content();root.innerHTML=heading('My library','Your reading and borrowing overview.')+'<div id="student-dashboard" class="loading">Loading dashboard…</div>';const data=await api.studentDashboard();root.querySelector('#student-dashboard').outerHTML=`<div class="stats">${stat('Currently borrowed',data.currently_borrowed,'↗')}${stat('Pending requests',data.pending_requests,'◌')}${stat('Approved requests',data.approved_requests,'✓')}${stat('Overdue books',data.overdue_books,'!')}</div><section class="card section-card"><h3>Recent requests</h3>${requestTable(data.recent_requests||[])}</section>`;}
function requestTable(rows){return rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Book</th><th>Requested</th><th>Status</th><th>Note</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${escapeHtml(row.book_title)}</td><td>${escapeHtml(row.request_date)}</td><td>${badge(row.status)}</td><td>${escapeHtml(row.rejection_reason||'—')}</td></tr>`).join('')}</tbody></table></div>`:empty('You have not made a request yet.');}
async function booksPage(){const root=content();root.innerHTML=heading('Browse books','Search the library collection and request available titles.')+`<section class="card"><div class="toolbar"><input class="field search" id="catalogue-search" placeholder="Search title, author or ISBN"><input class="field" id="catalogue-category" placeholder="Filter category"><select class="field" id="catalogue-availability"><option value="">All books</option><option value="AVAILABLE">Available now</option><option value="UNAVAILABLE">Currently unavailable</option></select></div><div id="book-grid" class="book-grid" style="padding:16px"></div></section>`;const reload=async()=>{const grid=root.querySelector('#book-grid');setLoading(grid);const data=await api.books({search:root.querySelector('#catalogue-search').value,category:root.querySelector('#catalogue-category').value,availability:root.querySelector('#catalogue-availability').value});const rows=items(data);grid.innerHTML=rows.length?rows.map(book=>`<article class="card book-card"><div class="book-spine"></div><h3>${escapeHtml(book.title)}</h3><p class="author">${escapeHtml(book.author)}</p><p class="author">${escapeHtml(book.category)}</p><div class="meta"><span>${book.available_quantity} of ${book.total_quantity} available</span><button class="link-button view-book" data-id="${book.id}">Details</button></div></article>`).join(''):empty('No titles match your search.');};root.querySelector('#catalogue-search').oninput=debounce(reload);root.querySelector('#catalogue-category').oninput=debounce(reload);root.querySelector('#catalogue-availability').onchange=reload;root.addEventListener('click',async event=>{if(!event.target.matches('.view-book'))return;const book=await api.book(event.target.dataset.id);showModal(book.title,`<div class="form-grid"><div class="full split-info"><div class="info"><span>Author</span><strong>${escapeHtml(book.author)}</strong></div><div class="info"><span>Category</span><strong>${escapeHtml(book.category)}</strong></div><div class="info"><span>ISBN</span><strong>${escapeHtml(book.isbn)}</strong></div><div class="info"><span>Publisher</span><strong>${escapeHtml(book.publisher)}</strong></div><div class="info"><span>Published</span><strong>${escapeHtml(book.publication_year)}</strong></div><div class="info"><span>Availability</span><strong>${book.available_quantity} / ${book.total_quantity}</strong></div></div></div>`,async()=>{await api.requestBook(Number(book.id));toast('Book request submitted.');},book.available_quantity>0?'Request book':'Request unavailable');if(!Number(book.available_quantity))document.querySelector('.modal .submit').disabled=true;});await reload();}
async function requestsPage(){const root=content();root.innerHTML=heading('My requests','Follow the status of your requested books.')+'<div id="requests-table" class="loading">Loading requests…</div>';const data=await api.myRequests();root.querySelector('#requests-table').innerHTML=table(['Book','Requested','Status','Processed','Reason'],items(data).map(row=>`<tr><td>${escapeHtml(row.book_title)}<br><small>${escapeHtml(row.author)}</small></td><td>${escapeHtml(row.request_date)}</td><td>${badge(row.status)}</td><td>${escapeHtml(row.processed_date||'—')}</td><td>${escapeHtml(row.rejection_reason||'—')}</td></tr>`),'You have no book requests.');}
function issuesTable(rows,history=false){return table(['Book','Issue date','Due date','Return date','Status','Fine'],rows.map(row=>`<tr><td>${escapeHtml(row.book_title)}<br><small>${escapeHtml(row.author)}</small></td><td>${row.issue_date}</td><td>${row.due_date}</td><td>${row.return_date||'—'}</td><td>${badge(row.status)}${!history&&row.due_date<new Date().toISOString().slice(0,10)?' '+badge('OVERDUE'):''}</td><td>${Number(row.fine||0).toFixed(2)}</td></tr>`),history?'Your borrowing history is empty.':'You have no books issued at the moment.');}
async function myBooksPage(){const root=content();root.innerHTML=heading('My books','Books currently issued to your account.')+'<div id="my-books" class="loading">Loading active books…</div>';const data=await api.myBooks();root.querySelector('#my-books').innerHTML=issuesTable(items(data));}
async function historyPage(){const root=content();root.innerHTML=heading('Borrowing history','Your complete borrowing record.')+'<div id="history" class="loading">Loading history…</div>';const data=await api.history();root.querySelector('#history').innerHTML=issuesTable(items(data),true);}
async function profilePage(){const root=content();root.innerHTML=heading('My profile','Your library account information.')+'<div id="profile" class="loading">Loading profile…</div>';const data=await api.studentProfile();root.querySelector('#profile').outerHTML=`<section class="card section-card"><div class="split-info"><div class="info"><span>Student ID</span><strong>${escapeHtml(data.student_code)}</strong></div><div class="info"><span>Name</span><strong>${escapeHtml(data.name)}</strong></div><div class="info"><span>Email</span><strong>${escapeHtml(data.email)}</strong></div><div class="info"><span>Phone</span><strong>${escapeHtml(data.phone)}</strong></div><div class="info"><span>Department</span><strong>${escapeHtml(data.department)}</strong></div><div class="info"><span>Course and year</span><strong>${escapeHtml(data.course)} · Year ${escapeHtml(data.study_year)}</strong></div></div></section>`;}
function debounce(fn){let timer;return()=>{clearTimeout(timer);timer=setTimeout(fn,260);};}
const handlers={dashboard,books:booksPage,requests:requestsPage,'my-books':myBooksPage,history:historyPage,profile:profilePage};const user=await mountPortal('student');if(user){try{await handlers[page](user);}catch(error){content().innerHTML=heading('Something went wrong')+`<div class="card">${empty(error.message)}</div>`;toast(error.message,true);}}
